spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fleetscan?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: taxiuser
    password: taxi123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


logging:
  level:
    org.hibernate: DEBUG
    com.fleetScan: DEBUG

telegram:
  bot:
    token: "8219016516:AAET9RoCVdiVG1ymoA60h5I49HaHx_yVsS8"
    name: "fleetScanBot"
